FROM rabbitmq

# Define environment variables.
ENV RABBITMQ_USER myuser
ENV RABBITMQ_PASSWORD mypassword

ADD ./config/rabbitmq config
RUN chmod u+x config/*.sh

# Define default command
CMD ["./config/init.sh"]
