FROM docker.elastic.co/beats/filebeat:7.6.1
MAINTAINER Yoonjae Park <yj0604.park@gmail.com>
USER root

RUN mkdir /work
RUN chown filebeat:filebeat /work
# WORKDIR /work

USER filebeat

# ADD --chown=filebeat:filebeat /work/wait-for-it.sh .
ADD --chown=filebeat:filebeat ./config/filebeat/filebeat.yml /usr/share/filebeat/filebeat.yml
ADD --chown=filebeat:filebeat ./scripts/filebeat.sh .

# RUN chown filebeat:filebeat ./filebeat.sh
# RUN chown -R filebeat:filebeat /work