version: '3'

volumes:
  production_logs: {}

services:
  rabbitmq:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile_rabbitmq

  celery: &celery
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    depends_on:
      - rabbitmq
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile
    volumes:
      - ./:/work
    command: ["./wait-for-it.sh", "rabbitmq:5672", "--", "/scripts/run_celery.sh"]

  django:
    <<: *celery
    shm_size: '512MB'
    ports:
      - "38000:8000"
    command:
      - /scripts/run_gunicorn.sh

  flower:
    <<: *celery
    ports:
      - "5555:5555"
    command: ["./wait-for-it.sh", "rabbitmq:5672", "--", "/scripts/run_flower.sh"]

  nginx:
    image:
      "nginx:latest"
    ports:
      - "80:80"
    volumes:
      - /var/www:/usr/share/nginx/html:ro
      - ./config/nginx:/etc/nginx/conf.d
      - ./:/work
      - production_logs:/work/log/nginx
    command: ["/work/dashboard/wait-for-it.sh", "django:38000", "--", "nginx", "-g", "daemon off;"]

  filebeat:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile_filebeat
    env_file:
      - ./.envs/.production/.filebeat
    volumes:
      - production_logs:/var/log/nginx
    command: ["./filebeat.sh"]

