version: '3'

services:
  rabbitmq:
    image:
      "rabbitmq:latest"

  django:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "38000:8000"
    volumes:
      - ./:/work
    command:
      - ./run_server.sh

  celery:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/work
    command: ["./wait-for-it.sh", "db:5672", "--", "./celery.sh"]