version: '3'

services:
  rabbitmq:
    image:
      "rabbitmq:latest"

  django:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "38000:8000"
    volumes:
      - ./:/work
    command:
      - ./run_gunicorn.sh

  celery:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/work
    command: ["./wait-for-it.sh", "db:5672", "--", "./celery.sh"]

  nginx:
    image:
      "nginx:latest"
    ports:
      - "80:80"
    volumes:
      - /var/www:/usr/share/nginx/html:ro
      - ./config/nginx:/etc/nginx/conf.d
      - ./dashboard/:/work
    command: ["/work/wait-for-it.sh", "django:38000", "--", "nginx", "-g", "daemon off;"]