version: '3'

services:
  rabbitmq:
    build:
      context: .
      dockerfile: ./Dockerfile_rabbitmq

  django:
    build:
      context: .
      dockerfile: ./Dockerfile
    shm_size: '512MB'
    ports:
      - "38000:8000"
    volumes:
      - ./:/work
    environment:
      - DEBUG=False
    command:
      - ./run_gunicorn.sh

  celery:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/work
    command: ["./wait-for-it.sh", "rabbitmq:5672", "--", "./celery.sh"]

  nginx:
    image:
      "nginx:latest"
    ports:
      - "80:80"
    volumes:
      - /var/www:/usr/share/nginx/html:ro
      - ./config/nginx:/etc/nginx/conf.d
      - ./:/work
    command: ["/work/dashboard/wait-for-it.sh", "django:38000", "--", "nginx", "-g", "daemon off;"]

  filebeat:
    build:
      context: .
      dockerfile: ./Dockerfile_filebeat
    environment:
      - ES_HOST
      - KIBANA_HOST
    volumes:
      - ./log/nginx:/var/log/nginx
      - ./env.sh:/work/env.sh
    command: ["/work/filebeat.sh"]