# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - welcome/run
      - docker-compose up -d
      - docker-compose -f local.yml build --quiet postgres django  2>&1 > /dev/null
      - docker-compose -f local.yml up -d postgres  2>&1 > /dev/null
      - docker-compose -f local.yml run --rm django bash -c "python3 manage.py makemigrations"
      - docker-compose -f local.yml run --rm django bash -c "python3 manage.py migrate"
      - docker-compose -f local.yml run --rm django bash -c "coverage run -m pytest"
      - docker-compose -f local.yml run --rm django bash -c "coverage report"
